# Generated by Django 2.0 on 2019-04-30 13:02

from django.db import migrations, models
import portal.validators


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20190429_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=10, unique=True, validators=[portal.validators.phone_number_validator], verbose_name='phone number'),
        ),
    ]
