# Generated by Django 2.0 on 2019-05-01 15:36

from django.db import migrations, models
import portal.validators


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20190430_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=13, unique=True, validators=[portal.validators.phone_number_validator], verbose_name='phone number'),
        ),
    ]
