# Generated by Django 2.0 on 2019-06-11 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('recharges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='recharge',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recharges.Recharge'),
        ),
    ]
