# Generated by Django 2.0 on 2019-05-18 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20190518_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='recharge',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recharges.Recharge'),
        ),
    ]
