# Generated by Django 2.0 on 2019-06-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bw_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('color_rate', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
