# Generated by Django 2.0 on 2019-05-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=6, unique=True)),
                ('water_mark', models.FileField(blank=True, null=True, upload_to='station/water_marks/')),
                ('coordinates', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('locality', models.CharField(blank=True, max_length=32)),
                ('city', models.CharField(blank=True, max_length=32)),
                ('embed_code', models.TextField(blank=True)),
                ('details', models.TextField(blank=True)),
            ],
        ),
    ]
