# Generated by Django 2.0 on 2019-06-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='link',
            field=models.TextField(blank=True),
        ),
    ]
