# Generated by Django 2.0 on 2019-05-31 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0001_initial'),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('color_name', models.CharField(blank=True, max_length=32)),
                ('color_hex_code', models.CharField(blank=True, max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='station',
            name='dealer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='dealers.Dealer'),
            preserve_default=False,
        ),
    ]
