# Generated by Django 2.0 on 2019-06-01 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_auto_20190531_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='station_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stations.StationClass'),
            preserve_default=False,
        ),
    ]
