# Generated by Django 2.0 on 2019-06-01 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_station_station_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='station_class',
        ),
    ]
