# Generated by Django 2.0 on 2019-06-04 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
        ('stations', '0003_station_station_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stationclass',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stationclass',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stationclass',
            name='rate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rates.Rate'),
            preserve_default=False,
        ),
    ]
