# Generated by Django 2.0 on 2019-06-01 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dealers', '0001_initial'),
        ('stations', '0004_remove_station_station_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalStation',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('code', models.CharField(db_index=True, max_length=6)),
                ('water_mark', models.TextField(blank=True, max_length=100, null=True)),
                ('coordinates', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('locality', models.CharField(blank=True, max_length=32)),
                ('city', models.CharField(blank=True, max_length=32)),
                ('embed_code', models.TextField(blank=True)),
                ('details', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('dealer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dealers.Dealer')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('station_class', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stations.StationClass')),
            ],
            options={
                'verbose_name': 'historical station',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='station',
            name='station_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stations.StationClass'),
            preserve_default=False,
        ),
    ]
