# Generated by Django 2.0 on 2019-06-09 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_auto_20190604_1242'),
        ('stations', '0005_auto_20190601_1859'),
    ]

    operations = [
    ]
