# Generated by Django 2.0 on 2019-06-11 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('otp_1', models.CharField(max_length=4)),
                ('otp_2', models.CharField(max_length=4)),
                ('file', models.FileField(upload_to='transactions/transaction_files/2019-06-11/')),
                ('payment_mode', models.CharField(choices=[('AC', 'Account'), ('CO', 'Coin')], max_length=2)),
                ('color_model', models.CharField(choices=[('BW', 'Black&White'), ('CL', 'Colorful')], default='BW', max_length=2)),
                ('copies', models.PositiveSmallIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pages', models.PositiveSmallIntegerField()),
                ('paper_type', models.CharField(choices=[('NM', 'Normal'), ('LT', 'Letter'), ('PP', 'Photo Paper')], default='NM', max_length=2)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_printed', models.BooleanField(default=False)),
                ('printed_on', models.DateTimeField(blank=True, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_permitted', models.BooleanField(default=True)),
                ('details', models.TextField(blank=True)),
                ('printed_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stations.Station')),
                ('station_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.StationClass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
