# Generated by Django 2.0 on 2019-06-04 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_auto_20190604_1242'),
        ('transactions', '0002_auto_20190601_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='printed',
            new_name='is_printed',
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_permitted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='pages',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='station_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stations.StationClass'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='file',
            field=models.FileField(upload_to='transactions/transaction_files/2019-06-04/'),
        ),
    ]
