# Generated by Django 2.0 on 2019-06-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20190619_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.CharField(blank=True, choices=[('JPG', 'JPG'), ('PNG', 'PNG'), ('PDF', 'PDF'), ('TXT', 'TXT')], max_length=3),
        ),
    ]
