# Generated by Django 2.0 on 2019-06-08 15:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20190608_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
