# Generated by Django 2.0 on 2019-06-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20190619_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='has_error',
            field=models.BooleanField(default=False),
        ),
    ]
