# Generated by Django 2.0 on 2019-06-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_transaction_is_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_show',
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
