# Generated by Django 2.0 on 2019-06-22 10:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_auto_20190622_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='converted_file',
            field=models.FileField(blank=True, null=True, upload_to='transactions/files/converted_files/2019-06-22/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg', 'pdf'))]),
        ),
        migrations.AlterField(
            model_name='file',
            name='input_file',
            field=models.FileField(upload_to='transactions/files/input_files/2019-06-22/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg', 'pdf'))]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.File'),
        ),
    ]
