# Generated by Django 2.0 on 2019-06-22 10:09

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_auto_20190622_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='converted_file',
            field=models.FileField(blank=True, null=True, upload_to='transactions/files/converted_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg', 'pdf'))]),
        ),
        migrations.AlterField(
            model_name='file',
            name='input_file',
            field=models.FileField(upload_to='transactions/files/input_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg', 'pdf'))]),
        ),
    ]
