# Generated by Django 2.0 on 2019-05-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharges', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custompack',
            old_name='price',
            new_name='balance',
        ),
        migrations.AddField(
            model_name='recharge',
            name='payment_success',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recharge',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
