# Generated by Django 2.0 on 2019-06-04 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recharges', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerpack',
            old_name='active',
            new_name='is_active',
        ),
    ]
